site_name: "Emertyst 的博客"
theme:
  favicon: assets/favicon.png
  features:
    - content.code.copy
  font:
    code: "Jetbrains Mono"
    ligature: true
  language: "zh"
  logo: assets/favicon.png
  name: "material"
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
      line_spans: __span
  - pymdownx.superfences
  - pymdownx.tilde:
      subscript: false
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - 简介: index.md
  - 网络流:
    - 最大流与最小割: notes/network-flows/1.md
    - 最小割树: notes/network-flows/2.md
    - 费用流: notes/network-flows/3.md
    - 上下界网络流: notes/network-flows/4.md
  - 数据结构:
    - 红黑树: notes/data-structure/1.md
  - 动态规划:
    - 四边形不等式: notes/dp/1.md
  - 数学:
    - 多项式全家桶: notes/math/1.md
    - Miller Rabin: notes/math/2.md
    - 行列式: notes/math/3.md
    - 广义容斥原理与二项式反演: notes/math/4.md
    - 莫比乌斯反演: notes/math/5.md
  - 字符串:
    - 简介: notes/string/index.md
    - KMP: notes/string/1.md
    - Z 函数: notes/string/2.md
  - Windows API:
    - 简介: notes/winapi/index.md
    - 入门: notes/winapi/1.md
  - 杂项:
    - 文件 IO: notes/misc/1.md
    - 黑科技: notes/misc/2.md
  - 一些封装:
    - 模意义下 int: template/mod-int.md
    - 高精度整数: template/big-integer.md
  - cymrain07 的宝藏:
    - fhq-Treap 合并的技巧: cymrain07/1.md
    - Splay 的 Finger-Search 优化启发式合并: cymrain07/2.md
    - 多项式公式总结: cymrain07/3.md
    - 二逼平衡树的各种神奇的数据结构的时空及代码长度: cymrain07/4.md